### ISSUE TITLE
general documentation issues

### ISSUE THREAD

**Issue by 3052** [PackOrganization/Pack#1]
If I go here:

https://pack.ac/

it seems like someone tried to make the site single page, but its not:

> ![Untitled](https://github.com/PackOrganization/Pack/assets/147215885/23519fd4-8ea1-470a-b8e2-cf0a33b0f209)

another issue, the main page also has basically nothing. the main should should be either the "notes" page or the "documentation" page. also if I click Notes, the URL does not update, so I cannot link someone directly to the notes. also, the notes page runs off the screen, with no scroll bar:

> ![2](https://github.com/PackOrganization/Pack/assets/147215885/19789d32-6bce-48d5-9428-b05872c35d0a)

further, the notes "page" appears to have no navigation whatsoever, not "up", "back", nothing. the user is left to guess what to do. if I click the black area, it goes "back". overall the site just seems over engineered and unpleasant to use.

**Comment by erentar** [comment]
I also had difficulty navigating the website

**Comment by OttoCoddo** [comment]
The Notes page now shows the correct URL. 
Site will get some improvement later on, but if you faced any particular issue, please open a separate issue with clear information.

**Comment by 3052** [comment]
how could it be any clearer? I offered detailed info WITH pictures. if you don't want to fix it, just say that.

**Comment by OttoCoddo** [comment]
I meant the bug you noted is fixed, and any other bug should be reported, as you reported clearly. It was a general note for the other commenter.
And as I said, the site will get general improvement. But if you see any bugs, let me know.

Thank you for the report.

**Comment by softyoda** [comment]
I think it would be general usage to add some basic documentation / description inside the readme.md of this repo. (as a way to archive knowledge)
