### ISSUE TITLE
Error: Unknown parameter

### ISSUE THREAD

**Issue by setop** [PackOrganization/Pack#11]
```
pack --list linux.pack 
Error: Unknown parameter: linux.pack
Press Enter key to exit
```

```
/pack --list 
Error: Missing input
Press Enter key to exit
```

**Comment by OttoCoddo** [comment]
You need to use `--input` or `-i` if you want to use other parameters.
Quick mode as `pack test.pack` is only accepted with no other parameters and works only for packing and unpacking.
Check https://pack.ac/cli-documentation for more information.
