### ISSUE TITLE
Windows Defender reports as virus

### ISSUE THREAD

**Issue by roygrubb** [PackOrganization/Pack#5]
Windows Defender reports pack.exe as a virus and blocks downloading.

virustotal reports: "No security vendors flagged this URL as malicious : https://pack@releases/windows/pack.exe
Last Analysis Date: 1 month ago

**Comment by OttoCoddo** [comment]
It is a false report.
It happens from time to time, and the only way (except by buying a license from Microsoft) to make it happy is to report it to Defender, who will recheck and clear it.
https://www.microsoft.com/en-us/wdsi/filesubmission

I just did it now, but if as I am not getting the error here and if you want to get an update on your machine sooner, I suggest doing it yourself too. It takes a minute.

Thank you for the issue.

**Comment by roygrubb** [comment]
Unfortunately, MS don't support a URL submission, unlike Virustotal.  
As Windows Defender prevents me downloading it, I can't submit an executable, so MS rejects my submission.  
Snake bites its own tail!
So then I tried turning WD off, downloaded pack.exe, but it doesn't run.  Nothing happens.
Also tried adding pack.exe as an exclusion.  Same.
Frustrating.
Will try in a few days.

**Comment by OttoCoddo** [comment]
I guess your Windows Defender is not up to date.
Please check for updates and restart.

**Comment by roygrubb** [comment]
Did that, and WD did update, I rebooted, but it's still supressing download at https://pack.ac/releases/windows/pack.exe as a virus and killing the download.  Irksome.

I'll give it a try in a day or two.

**Comment by OttoCoddo** [comment]
I got back answer from Microsoft on submission of latest CLI on the site:

> Analyst comments:
> 
> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

You can try this and see if it resolves the issue for you.

**Comment by roygrubb** [comment]
Updated WD this morning, rebooted.  Now I'm able to download pack.exe without WD stepping in.  Yesterday I had set an exception for pack.exe in WD after downloading with WD turned off - removed that.  Right clicked on pack.exe, selected Scan with Microsoft Defender: "No current threats."

All good now, thanks.

**Comment by OttoCoddo** [comment]
Thank you for the report and checking. Have fun packing.
