### ISSUE TITLE
Feature request... kinda :stuck_out_tongue: 

### ISSUE THREAD

**Issue by gcarreno** [PackOrganization/Pack#7]
Hey Mr. **Pack**man(@OttoCoddo),

Would like to see a version number somewhere on the site or on the GitHub repo.

I acknowledge that maybe the downloaded binary will provide that for me once I run it with `-v`, but it's nice for those of us( I know, I'm aware I'm a freak :wink: ) that like to have an historic of the various versions.

Maybe the download on the site is not the binary, but an archive of the binary, something like `pack-v0.1.tar.gz`, which also will make us not have to `chmod +x pack` every time we download a new version. And I propose an alternate to the `.pack` format, so we don't incur in a chicken and egg conundrum.

:thinking: .oO( I swear, these Windows users and their lack of knowledge of the Linux culture... :smile_cat: :stuck_out_tongue: )

Cheers,
Gus
P.S.: I officially declare they be renamed to Mr. **Pack**man!! Can even attempt at starting a crowfund for the legal fees to make the legal name change :stuck_out_tongue_winking_eye:

**Comment by OttoCoddo** [comment]
Hey, Gus, and thank you for the notes.

- There is one in the download section (Other downloads): https://pack.ac
- When you get the source, the project file and source are marked with the correct version.
- Source is available at this repo to prevent the chicken-and-egg problem.
- Later on, improved packaging or installer  will be released for each platform. Even then, it will be available for GUI and OS integration.
- People who download CLI alone, know about permissions, and I argue it is better for them to choose to allow a new binary to execute.
- Others, who get the official package, installer, or build from source, will not need to do that.

I like the name; it is fun. Thank you!

**Comment by gcarreno** [comment]
Hey Mr. Packman(@OttoCoddo),

You and your long answers when I'm about to head to bed!!

I'll sleep on it and answer your, oh so nice, bullet points later!! :people_hugging: 

Cheers,
Gus
