### ISSUE TITLE
Missing params

### ISSUE THREAD

**Issue by gcarreno** [PackOrganization/Pack#8]
Hey Mr. Packman(@OttoCoddo),

WDYM, unknown param?!?!?!?
```console
$ ./pack -v
Error: Unknown parameter: v
Press Enter key to exit
$ ./pack -h
Error: Unknown parameter: h
Press Enter key to exit
```

And "Press Enter key to exit"?!?!?!

Needs some revision :smiley_cat: 

:thinking: .oO( I swear, and double swear, these Windows users.... :smile: )

Cheers,
Gus

**Comment by OttoCoddo** [comment]
The choice of parameters was solely done to be clear, and not what people used to. -f meaning force is not clear; -w meaning overwrite, seemed like a better logical choice, to me.

Nice point on -h. Yes, I did not want to go crazy. After all, almost all (CLI) people use pack as `pack ./test/`. Options are for advanced people like you.

For now `--help` is available. https://pack.ac/cli-documentation

**Comment by gcarreno** [comment]
Hey Mr. Packman(@OttoCoddo),

Sorry to strongly disagree with:
> Options are for advanced people like you.

99.9% of the Linux crowd will interact with your tool on their first try with:
```console
$ pack -h
```

This should provide a sensible usage printout with a list of all possible params and a small description of their function.

It's something that all Linux users get a muscle memory of, whatever their skill level.

Cheers,
Gus
